### ISSUE TITLE
return するリストの型について

### ISSUE THREAD

**Issue by myuuuuun** [13tsuyoshi/DA_algorithms#6]
DAアルゴリズムを動かす関数がnumpy.ndarrayを返すようになっていますが、PythonのArrayじゃなくても良いのでしょうか

Issueを使ってみる。

**Comment by oyamad** [comment]
それはコードを書く人の選択です．

(`test_matching.py` では numpy の ndarray でも pure Python の list でも tuple でも，内容が正しければ通るようになっています．というか，`assert_array_equal` がそういう仕様です．)

**Comment by myuuuuun** [comment]
ならよかったです.
